# -*- coding: utf-8 -*-
"""
compare_arrays.py
=================
Gate C1 against every standard array at full size for the 21-electrode set:
Wenner, Schlumberger, dipole-dipole, pole-dipole, pole-pole. Each canonical
scheme is generated by pygimli at full size, its Jacobian built on the same
width-0.2 soft forward, and its Gamma(n) scored in its own (fixed) order. Greedy-D
on the comprehensive pool is the champion line; random-from-pool is reference.

Notes / honesty flags:
  * The comprehensive pool is the 4-distinct-electrode space, so greedy can select
    anything Wenner/Schlumberger/dd/pole-dipole offer EXCEPT pole configurations
    (remote electrode at infinity). Pole-pole / pole-dipole are shown as baselines,
    not as options available to greedy.
  * Pole arrays place an electrode at infinity; on a bounded 2D mesh their forward
    is the least reliable of the five -- treat their curves with caution. The code
    reports which schemes built and at what size.
  * All comparisons are at the true-theta Jacobian (optimistic). Prior-mean
    robustness is the next check, not this one.

Run in ERT_GUI. Needs oed_c1.py, oed_linearized.py, build_pool.py,
pwhg_forward_soft.py, pwhg_wrapper.py, validate_soft.py, validate_sensitivity.py.
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import pygimli.physics.ert as ert

import pwhg_wrapper as W
from pwhg_forward_soft import SoftTriForward
from validate_soft import PRIOR_STD
from oed_c1 import choose_steps_hisnr
from oed_linearized import (_sequential, _greedy_D, _fixed,
                            _random_order_fn, n_to_target)


ARRAYS = {
    "Wenner":        ["wa"],
    "Schlumberger":  ["slm", "schlumberger"],
    "Dipole-dipole": ["dd"],
    "Pole-dipole":   ["pd", "pole-dipole"],
    "Pole-pole":     ["pp", "pole-pole"],
}


def _make_scheme(elec_x, aliases):
    for name in aliases:
        try:
            s = ert.createData(elecs=elec_x, schemeName=name)
            if s.size() > 0:
                return s
        except Exception:
            continue
    return None


def run(world, pool, steps, budget=120, target=0.1, n_random=10,
        out="oed_arrays.png"):
    labels = W.param_labels(world)
    theta0 = np.asarray(world.get_x0(), float)
    elec_x = np.array(world.scheme.sensorPositions())[:, 0]
    prior_std = np.array([PRIOR_STD[k] for _, k in labels])
    prior_var = prior_std ** 2
    Pi0 = W.prior_precision(prior_std)

    # champion: greedy-D on comprehensive pool
    soft = SoftTriForward(world, width=0.2, scheme=pool)
    _, rhoa0 = soft.forward(theta0)
    eps = W.noise_std(soft, rhoa0)
    J, _, _ = W.jacobian_generic(soft.forward, theta0, steps)
    gd = _sequential(J, eps, Pi0, prior_var, _greedy_D, budget)
    rnd = [_sequential(J, eps, Pi0, prior_var,
                       _random_order_fn(np.random.default_rng(s)), budget)
           for s in range(n_random)]
    rnd_gamma = np.mean([r["gamma"] for r in rnd], axis=0)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.semilogy(gd["gamma"], lw=2.2, color="k", label="greedy-D (comprehensive)")
    ax.semilogy(rnd_gamma, lw=1, color="gray", ls=":", label="random from pool")

    print(f"\n{'scheme':<15}{'size':>7}{'n@target':>10}{'Gamma_final':>13}")
    print(f"{'greedy (comp.)':<15}{pool.size():>7}"
          f"{str(n_to_target(gd['gamma'], target)):>10}{gd['gamma'][-1]:>13.2e}")

    for nm, aliases in ARRAYS.items():
        scheme = _make_scheme(elec_x, aliases)
        if scheme is None:
            print(f"{nm:<15}{'--':>7}   (createData failed / unsupported)")
            continue
        soft_a = SoftTriForward(world, width=0.2, scheme=scheme)
        try:
            _, rhoa_a = soft_a.forward(theta0)
        except Exception as e:
            print(f"{nm:<15}{scheme.size():>7}   forward failed: {e}")
            continue
        eps_a = W.noise_std(soft_a, rhoa_a)
        J_a, _, _ = W.jacobian_generic(soft_a.forward, theta0, steps)
        fx = _sequential(J_a, eps_a, Pi0, prior_var, _fixed, scheme.size())
        n_t = n_to_target(fx["gamma"], target)
        ax.semilogy(fx["gamma"], lw=1.3, label=f"{nm} (n={scheme.size()})")
        print(f"{nm:<15}{scheme.size():>7}{str(n_t):>10}{fx['gamma'][-1]:>13.2e}")

    ax.axhline(target, color="gray", ls="--", lw=1)
    ax.set_xlabel("n measurements"); ax.set_ylabel("Gamma (max var ratio)")
    ax.set_title("Gate C1: greedy vs standard arrays at full size")
    ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(out, dpi=140); plt.close(fig)
    print(f"figure: {out}")


def main():
    from validate_sensitivity import build_c11_world
    from build_pool import build_comprehensive_pool
    world = build_c11_world()
    pool, _ = build_comprehensive_pool(world, u_floor=5e-3)
    soft = SoftTriForward(world, width=0.2, scheme=pool)
    theta0 = np.asarray(world.get_x0(), float)
    _, rhoa0 = soft.forward(theta0)
    eps = W.noise_std(soft, rhoa0)
    steps = choose_steps_hisnr(soft, theta0, eps)
    run(world, pool, steps)


if __name__ == "__main__":
    main()
